# Generated by Django 3.2.4 on 2021-07-05 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, unique=True)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='uploads/category/items/')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('quantity_type', models.CharField(choices=[('PU', 'Per Unit'), ('PC', 'Per Carton')], max_length=2)),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocka_api.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stocka_api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('quantity_type', models.CharField(choices=[('PU', 'Per Unit'), ('PC', 'Per Carton')], max_length=2)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('barcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stocka_api.productbarcode')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocka_api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('quantity_type', models.CharField(choices=[('PU', 'Per Unit'), ('PC', 'Per Carton')], max_length=2)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('barcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stocka_api.productbarcode')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocka_api.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocka_api.vendor'),
        ),
    ]
