# Generated by Django 3.0 on 2021-07-15 20:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, unique=True)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='uploads/category/items/')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('quantity_type', models.CharField(choices=[('PU', 'Per Unit'), ('PC', 'Per Carton')], default='PC', max_length=2)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('item_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocka_api.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('quantity_type', models.CharField(choices=[('PU', 'Per Unit'), ('PC', 'Per Carton')], default='PC', max_length=2)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_sales_made', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocka_api.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('quantity_type', models.CharField(choices=[('PU', 'Per Unit'), ('PC', 'Per Carton')], default='PC', max_length=2)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_purchase_made', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocka_api.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocka_api.Vendor'),
        ),
    ]
