# Generated by Django 3.2.4 on 2021-07-05 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocka_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stocka_api.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_type',
            field=models.CharField(choices=[('PU', 'Per Unit'), ('PC', 'Per Carton')], default='PC', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='stocka_api.vendor'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity_type',
            field=models.CharField(choices=[('PU', 'Per Unit'), ('PC', 'Per Carton')], default='PC', max_length=2),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity_type',
            field=models.CharField(choices=[('PU', 'Per Unit'), ('PC', 'Per Carton')], default='PC', max_length=2),
        ),
    ]
