# Generated by Django 3.2.4 on 2021-07-07 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocka_api', '0005_auto_20210705_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='date_purchase_made',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sale',
            name='date_sales_made',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
